# Generated by Django 4.2.8 on 2023-12-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTypes',
            fields=[
                ('type', models.IntegerField(default=0, max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(default=0, max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.IntegerField(default=0, max_length=5, primary_key=True, serialize=False)),
                ('orderdate', models.DateField()),
                ('shippingdate', models.DateField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.product')),
            ],
        ),
    ]
